//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldFestSolution.WebAPI.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldFestBaseEntities : DbContext
    {
        public WorldFestBaseEntities()
            : base("name=WorldFestBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Festival> Festival { get; set; }
        public virtual DbSet<FestivalComment> FestivalComment { get; set; }
        public virtual DbSet<FestivalProgram> FestivalProgram { get; set; }
        public virtual DbSet<FestivalRating> FestivalRating { get; set; }
        public virtual DbSet<ParticipantInvite> ParticipantInvite { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRating> UserRating { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
    }
}
