//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldFestSolution.WebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FestivalComment
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Text { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public int FestivalId { get; set; }
    
        public virtual Festival Festival { get; set; }
        public virtual User User { get; set; }
    }
}
